port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
allow-lan: true
find-process-mode: off
mode: rule
log-level: warning
ipv6: true
external-controller: 0.0.0.0:9999
#secret: "Qjm12345"
proxies:
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: 自动
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
  - name: 手动
    type: select
    use:
      - provider1
      - provider2
  - name: 香港
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "HK|香港"
  - name: 台湾
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "TW|台湾"
  - name: 日本
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "JP|日本"
  - name: 韩国
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "KR|韩国"
  - name: 狮城
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "SG|新加坡|狮城"
  - name: 美国
    type: url-test
    tolerance: 100
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    use:
      - provider1
      - provider2
    filter: "US|美国"
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 境外AI
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: Apple
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: Github
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: YouTube
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: Google
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: Telegram
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: OneDrive
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
  - name: 国内
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
  - name: 其他
    type: select
    proxies:
      - 节点选择
      - 自动
      - 手动
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 狮城
      - 美国
      - DIRECT
proxy-providers:
  provider1:
    type: http
    url: "https://ghfast.top/https://raw.githubusercontent.com/qianjianmin/cl1/refs/heads/main/qjm1"
    interval: 86400
    path: tmp/proxy_provider/provider1.yaml
    health-check:
      enable: true
      interval: 86400
      url: https://www.gstatic.com/generate_204
  provider2:
    type: http
    url: "https://sub1.qjm95.ddns-ip.net/1024?sub=vless.cmliussss.net"
    interval: 86400
    path: tmp/proxy_provider/provider2.yaml
    health-check:
      enable: true
      interval: 86400
      url: https://www.gstatic.com/generate_204
rules:
  - RULE-SET,category-ads-all,广告拦截
  - RULE-SET,category-ai-chat-!cn,境外AI
  - RULE-SET,apple,Apple
  - RULE-SET,apple-cn,Apple
  - RULE-SET,github,Github
  - RULE-SET,youtube,YouTube
  - RULE-SET,google,Google
  - RULE-SET,google-cn,Google
  - RULE-SET,telegram,Telegram
  - RULE-SET,onedrive,OneDrive
  - RULE-SET,microsoft,微软服务
  - RULE-SET,geolocation-!cn,其他
  - RULE-SET,cn,国内
#  - IP-CIDR,10.0.0.0/8,DIRECT
#  - IP-CIDR,172.16.0.0/12,DIRECT
#  - IP-CIDR,192.168.0.0/16,DIRECT
#  - IP-CIDR,100.64.0.0/10,DIRECT
#  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,其他
rule-providers:
  category-ads-all:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/category-ads-all.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ads-all.yaml"
    interval: 86400
  category-ai-chat-!cn:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/category-ai-chat-!cn.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ai-chat-!cn.yaml"
    interval: 86400
  apple:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/apple.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/apple.yaml"
    interval: 86400
  apple-cn:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/apple-cn.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/apple-cn.yaml"
    interval: 86400
  github:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/github.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/github.yaml"
    interval: 86400
  youtube:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/youtube.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/youtube.yaml"
    interval: 86400
  google:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/google.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/google.yaml"
    interval: 86400
  google-cn:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/google-cn.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/google-cn.yaml"
    interval: 86400
  telegram:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/telegram.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/telegram.yaml"
    interval: 86400
  onedrive:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/onedrive.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/onedrive.yaml"
    interval: 86400
  microsoft:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/microsoft.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/microsoft.yaml"
    interval: 86400
  geolocation-!cn:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/geolocation-!cn.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/geolocation-!cn.yaml"
    interval: 86400
  cn:
    type: http
    behavior: classical
    format: yaml
    path: tmp/rule_provider/cn.yaml
    url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/cn.yaml"
    interval: 86400